services:
  postgres:
    image: postgres:15-alpine
    container_name: sit_postgres
    restart: always
    environment:
      POSTGRES_DB: sit_db
      POSTGRES_USER: sit_user
      POSTGRES_PASSWORD: sit_password
    ports:
      - "2024:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sit_user -d sit_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sit_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: sit_backend
    restart: always
    ports:
      - "1999:80"
    environment:
      APP_ENV: production
      APP_KEY: base64:aj8Ws2Bl7ID7XlVCLQOM3DMpWQORJBqsxj2829hrv3Q=
      APP_DEBUG: "false"
      APP_URL: https://demolms.rayan.web.id
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: sit_db
      DB_USERNAME: sit_user
      DB_PASSWORD: sit_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: database
      FRONTEND_URL: https://demolms.rayan.web.id
      SANCTUM_STATEFUL_DOMAINS: demolms.rayan.web.id,localhost:1999,localhost,127.0.0.1
      SESSION_DOMAIN: ""
    volumes:
      - backend_storage:/var/www/html/storage/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: sit_frontend
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  backend_storage:
